# Generated by Django 6.0.6 on 2026-06-17 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='A Marca deve conter no mínimo 2 caracteres e no máximo 25.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca')),
                ('modelo', models.CharField(help_text='O Modelo deve conter no mínimo 2 caracteres e no máximo 25.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('ano', models.IntegerField(help_text='O Ano deve ser no máximo o ano atual.', validators=[django.core.validators.MaxValueValidator(2026)], verbose_name='Ano')),
                ('placa', models.CharField(help_text='A Placa deve conter no máximo 8 caracteres.', max_length=8, verbose_name='Placa')),
                ('chassi', models.CharField(help_text='O Chassi deve ter no máximo 13 caracteres.', max_length=13, verbose_name='Chassi')),
                ('cor', models.CharField(help_text='A Cor deve conter no mínimo 4 caracterese no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor')),
                ('cor_lateral', models.CharField(help_text='A Cor Lateral deve conter no mínimo 4 caracterese no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor Lateral')),
                ('velocidade', models.FloatField(help_text='A Velocidade deve ser valor entre 0.0 e 500.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Velocidade')),
                ('tipo_combustivel', models.CharField(help_text='O Tipo de Combustivel deve ter no mínimo 2 caracteres e no máximo 15.', max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Tipo Combustivel')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
