# Generated by Django 6.0.6 on 2026-06-17 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.CharField(choices=[(1, 'Azul'), (2, 'Preto'), (3, 'Branco'), (4, 'Amarelo'), (5, 'Roxo')], default=1, help_text='A Cor deve conter no mínimo 4 caracteres e no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor_lateral',
            field=models.CharField(help_text='A Cor Lateral deve conter no mínimo 4 caracteres e no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor Lateral'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Byd', 'Build Your Dream - BYD'), ('Volkswagen', 'Volkswagen - VW'), ('Volvo', 'Volvo'), ('Renault', 'Renault'), ('Fiat', 'Fiat')], default='Byd', help_text='A Marca deve conter no mínimo 2 caracteres e no máximo 25.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Álcool', 'Álcool'), ('Diesel', 'Diesel'), ('Elétrico', 'Elétrico'), ('Álcool/Gasolina', 'Flex - Álcool/Gasolina'), ('Gasolina', 'Gasolina'), ('Híobrido', 'Híbrido - Gasolina/Elétrico')], default='Gasolina', help_text='O Tipo de Combustivel deve ter no mínimo 2 caracteres e no máximo 15.', max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Tipo Combustivel'),
        ),
    ]
