# Generated by Django 6.0.6 on 2026-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_alter_carro_cor_alter_carro_cor_lateral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.IntegerField(choices=[(1, 'Azul'), (2, 'Preto'), (3, 'Branco'), (4, 'Amarelo'), (5, 'Roxo')], default=1, help_text='A Cor deve conter no mínimo 4 caracteres e no máximo 20.', verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor_lateral',
            field=models.IntegerField(choices=[(1, 'Azul'), (2, 'Preto'), (3, 'Branco'), (4, 'Amarelo'), (5, 'Roxo')], default=1, help_text='A Cor Lateral deve conter no mínimo 4 caracteres e no máximo 20.', verbose_name='Cor Lateral'),
        ),
    ]
