# Generated by Django 6.0.6 on 2026-06-18 20:13

import aula.validators.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_alter_carro_cor_alter_carro_cor_lateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='numeros_pares',
            field=models.IntegerField(default=0, help_text='Insira o seu número escolhido. Lembre-se que apenas são aceitos números pares e únicos.', unique=True, validators=[aula.validators.functions.validar_par], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_combustivel',
            field=models.CharField(choices=[('Álcool', 'Álcool'), ('Diesel', 'Diesel'), ('Elétrico', 'Elétrico'), ('Álcool/Gasolina', 'Flex - Álcool/Gasolina'), ('Gasolina', 'Gasolina'), ('Híbrido', 'Híbrido - Gasolina/Elétrico')], default='Gasolina', help_text='O Tipo de Combustivel deve ter no mínimo 2 caracteres e no máximo 15.', max_length=15, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Tipo Combustivel'),
        ),
    ]
