# Generated by Django 6.0.6 on 2026-06-18 21:04

import aula.validators.code
import aula.validators.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_exemplo_numeros_pares_alter_carro_tipo_combustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='codigo',
            field=models.IntegerField(blank=True, help_text='Insira o código', null=True, validators=[aula.validators.code.CodeValidator(100)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='numeros_pares',
            field=models.IntegerField(default=0, help_text='Insira o seu número escolhido. Lembre-se que apenas são aceitos números pares e únicos.', unique=True, validators=[aula.validators.functions.validar_par, aula.validators.code.CodeValidator(200)], verbose_name='Número'),
        ),
    ]
