# Generated by Django 6.0.6 on 2026-06-18 21:46

import aula.validators.palavras_proibidas
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0006_exemplo_codigo_alter_exemplo_numeros_pares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Informe a descrição do exemplo, esta descrição ficará disponível para o usuário.', max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10), aula.validators.palavras_proibidas.PalavrasProibidas(['Inter', 'Admin', 'Root', 'Colorado'])], verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='titulo',
            field=models.CharField(help_text='O título deve conter pelo menos 5 caracteres e no máximo 100 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(5), aula.validators.palavras_proibidas.PalavrasProibidas(['Inter', 'Admin', 'Root'])], verbose_name='Título do Exemplo'),
        ),
    ]
