# Generated by Django 6.0.6 on 2026-06-24 17:42

import aula.validators.palavras_proibidas
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_alter_exemplo_descricao_alter_exemplo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplo',
            name='titulo',
            field=models.CharField(help_text='O título deve conter pelo menos 5 caracteres e no máximo 100 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(5), aula.validators.palavras_proibidas.PalavrasProibidas(['Inter', 'Admin', 'Root', 'Colorado'])], verbose_name='Título do Exemplo'),
        ),
    ]
