# Generated by Django 6.0.6 on 2026-06-25 19:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0008_alter_exemplo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='A Marca deve conter no mínimo 4 caracteres e no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Marca')),
                ('modelo', models.CharField(help_text='O Modelo deve conter no mínimo 2 caracteres e no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('ano', models.IntegerField(help_text='O Ano deve ser no mínimo 2021 e máximo o ano atual.', verbose_name='Ano')),
                ('alugado', models.BooleanField(default=False, help_text='Marque True se o carro for alugado.', verbose_name='Alugado')),
                ('placa', models.CharField(help_text='A placa deve ter no mínimo 7 caractres.', max_length=7, verbose_name='Placa')),
                ('valor_diaria', models.DecimalField(decimal_places=2, help_text='O valor da diária deve ser de no mínimo R$ 200,00.', max_digits=10, validators=[django.core.validators.MinValueValidator(200)], verbose_name='Valor Diária')),
                ('seguro', models.DecimalField(decimal_places=2, help_text='O seguro deve ser de no mínimo R$ 50,00.', max_digits=10, validators=[django.core.validators.MinValueValidator(50)], verbose_name='Seguro')),
                ('ultima_revisao', models.DateField(help_text='A última revisão pode ter no máximo a data do dia de hoje.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Última Revisão')),
                ('ipva', models.BooleanField(default=True, help_text='Marque False se o IPVA estiver atrasado.', verbose_name='IPVA')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
