# Generated by Django 6.0.6 on 2026-07-01 18:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0009_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome completo.', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de nascimento.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de nascimento')),
                ('cpf', models.CharField(help_text='Digite somente os números do CPF.', max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='alugado',
            field=models.BooleanField(default=False, help_text='Marque True se o marca for alugado.', verbose_name='Alugado'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(help_text='O Ano deve ser no mínimo 2021 e no máximo o ano atual.', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Lamborghini', 'Lamborghini'), ('Tesla', 'Tesla'), ('Bugatti', 'Bugatti')], default='Ford', help_text='A marca deve conter no mínimo 4 caracteres e no máximo 20.', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Marca'),
        ),
    ]
