# Generated by Django 6.0.6 on 2026-07-01 18:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0010_pessoa_alter_veiculo_alugado_alter_veiculo_ano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Insira o código alfanumérico do passaporte.', max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Número do Passaporte')),
                ('data_expedicao', models.DateField(help_text='Selecione a data de expedição do passaporte.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Expedição')),
                ('data_validade', models.DateField(editable=False, help_text='Selecione a data de validade do passaporte.', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de validade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
