# Generated by Django 6.0.6 on 2026-07-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0011_passaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='passaporte',
            name='pessoa',
            field=models.OneToOneField(blank=True, help_text='Selecione o titular do Passaporte.', null=True, on_delete=django.db.models.deletion.PROTECT, to='aula.pessoa'),
        ),
    ]
