# Generated by Django 6.0.6 on 2026-07-01 19:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0012_passaporte_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o Nome do Aluno, entre 2 e 120 caracteres.', max_length=120, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nome do Aluno')),
                ('cidade', models.CharField(help_text='Digite a cidade do aluno, entre 2 e 70 caracteres.', max_length=70, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cidade do Aluno')),
                ('universidade', models.CharField(help_text='Digite a Universidade do Aluno, entre 4 e 20 caracteres.', max_length=20, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Universidade do Aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(help_text='Digite o nome do Programa, entre 2 e 50 caracteres.', max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Programa')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Digite o valor da bolsa entre 0 e 14,000.', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14000)], verbose_name='Valor da bolsa')),
                ('data_inicio', models.DateField(help_text='Selecione a data de inicio da bolsa.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Inicio')),
                ('data_fim', models.DateField(help_text='Selecione a data de fim da bolsa.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de fim da Bolsa')),
                ('aluno', models.OneToOneField(help_text='Selecione o Aluno da Bolsa.', on_delete=django.db.models.deletion.PROTECT, to='aula.aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
