# Generated by Django 6.0.6 on 2026-07-01 19:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0013_aluno_bolsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='data_fim',
            field=models.DateField(help_text='Selecione a data de fim da bolsa.', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de fim da Bolsa'),
        ),
    ]
