# Generated by Django 6.0.6 on 2026-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0014_alter_bolsa_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsa',
            name='data_inicio',
            field=models.DateField(help_text='Selecione a data de inicio da bolsa.', verbose_name='Data de Inicio'),
        ),
    ]
