# Generated by Django 6.0.6 on 2026-07-02 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0015_alter_bolsa_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Informe o código do vôo comercial.', max_length=3, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Vôo Comercial')),
                ('data_hora', models.DateTimeField(help_text='Informe a data/horario de partida.', verbose_name='Data/Horário de Patida.')),
                ('origem', models.CharField(help_text='Informe o aeroporto de origem.', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('destino', models.CharField(help_text='Informe o aeroporto de destino.', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
