# Generated by Django 6.0.6 on 2026-07-02 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0016_voo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='cod',
            field=models.CharField(help_text='Informe o código do vôo comercial.', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Vôo Comercial'),
        ),
    ]
