# Generated by Django 6.0.6 on 2026-07-02 20:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0017_alter_voo_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(help_text='Informe o número da passagem no Vôo.', verbose_name='Número da Passagem')),
                ('passageiro', models.CharField(help_text='Informe o nome do passageiro.', max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('emitida', 'Emitida'), ('em processamento', 'Em Processamento'), ('cancelada', 'Cancelada')], help_text='Selecione o atual Status da passagem.', max_length=20)),
                ('poltrona', models.CharField(help_text='Informe a localização da poltrona.', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('voo', models.ForeignKey(help_text='Selecione o vôo comercial', on_delete=django.db.models.deletion.PROTECT, to='aula.voo', verbose_name='Vôo Comercial')),
            ],
            options={
                'verbose_name_plural': ('Passagens',),
                'unique_together': {('nr', 'voo'), ('passageiro', 'voo')},
            },
        ),
    ]
