# Generated by Django 6.0.6 on 2026-07-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0018_passagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passagem',
            options={'verbose_name_plural': 'Passagens'},
        ),
        migrations.AlterModelOptions(
            name='voo',
            options={'verbose_name_plural': 'Vôos'},
        ),
    ]
