# Generated by Django 6.0.6 on 2026-07-02 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0021_companhiaaerea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='voo',
            field=models.ForeignKey(help_text='Selecione o vôo comercial', on_delete=django.db.models.deletion.RESTRICT, to='aula.voo', verbose_name='Vôo Comercial'),
        ),
    ]
