# Generated by Django 6.0.7 on 2026-07-08 19:10

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0022_alter_passagem_voo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome completo do aluno entre 5 e 200 caracteres.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField(help_text='Selecione a data de nascimento do aluno.', validators=[django.core.validators.MinLengthValidator(datetime.date.today)], verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(help_text='Informe o número de CPF do aluno.', max_length=14, validators=[django.core.validators.RegexValidator(message='Informe o CPF no formato XXX.XXX.', regex='^\\d{3}.\\d{3}.\\d{3}-\\d{2}$.')])),
                ('curso', models.CharField(choices=[('Medicina', 'Medicina'), ('Programação', 'Programação'), ('Engenharia da Computação', 'Engenharia da Computação'), ('Letras', 'Letras'), ('Matematica', 'Matemática'), ('Fisica', 'Física'), ('Informática', 'Informática'), ('Ciência da Computação', 'Ciência da Computação')], help_text='Selecione o curso do aluno entre as opções possíveis.', max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome da disciplina.', max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('ementa', models.TextField(blank=True, help_text='Insira a ementa da disciplina até 5000 caracteres.', max_length=5000, null=True)),
                ('curso', models.CharField(choices=[('Medicina', 'Medicina'), ('Programação', 'Programação'), ('Engenharia da Computação', 'Engenharia da Computação'), ('Letras', 'Letras'), ('Matematica', 'Matemática'), ('Fisica', 'Física'), ('Informática', 'Informática'), ('Ciência da Computação', 'Ciência da Computação')], help_text='Selecione o curso da disciplina.', max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('carga_horaria', models.PositiveSmallIntegerField(help_text='Informe a carga horária da disciplina.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(160)], verbose_name='Carga Horária')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculado_em', models.DateTimeField(auto_created=True, help_text='Informe a data/hora da matrícula.')),
                ('ano', models.PositiveSmallIntegerField(help_text='Informe o ano da matrícula.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('semestre', models.PositiveSmallIntegerField(help_text='Informe o semestre da matrícula.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('frequencia', models.FloatField(help_text='Informe a frequência do estudante', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Frequência do estudante.')),
                ('nota', models.FloatField(help_text='Informe a nota do aluno.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('status', models.CharField(choices=[('Cancelada', 'Cancelada'), ('Matriculado', 'Matriculado'), ('Em Exame', 'Em Exame'), ('Aprovado', 'Aprovado'), ('Aprovado em Exame', 'Aprovado em Exame'), ('Reprovado por Média', 'Reprovado por Média'), ('Reprovado por Média/Frequência', 'Reprovado por Média/Frequência'), ('Reprovado por Frequência', 'Reprovado por Frequência')], help_text='Informe a nota final do aluno.', max_length=35, validators=[django.core.validators.MinLengthValidator(3)])),
                ('alterado_em', models.DateTimeField(auto_now=True, help_text='Informe a data/hora da alteração.')),
                ('aluno', models.ForeignKey(help_text='Selecione o aluno para matrícula.', on_delete=django.db.models.deletion.RESTRICT, to='aula.alunocurso')),
                ('disciplina', models.ForeignKey(help_text='Selecione a disciplina para a matrícula.', on_delete=django.db.models.deletion.RESTRICT, to='aula.disciplina')),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'ano', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, through='aula.Matricula', through_fields=('disciplina', 'aluno'), to='aula.alunocurso'),
        ),
    ]
