# Generated by Django 6.0.7 on 2026-07-08 19:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0023_alunocurso_disciplina_matricula_disciplina_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunocurso',
            name='data_nascimento',
            field=models.DateField(help_text='Selecione a data de nascimento do aluno.', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
    ]
