# Generated by Django 6.0.7 on 2026-07-08 19:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0024_alter_alunocurso_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunocurso',
            name='cpf',
            field=models.CharField(help_text='Informe o número de CPF do aluno.', max_length=14, validators=[django.core.validators.RegexValidator(message='Informe o CPF no formato XXX.XXX.XXX-XX', regex='^\\d{3}.\\d{3}.\\d{3}-\\d{2}$.')]),
        ),
        migrations.AlterField(
            model_name='alunocurso',
            name='data_nascimento',
            field=models.DateField(help_text='Selecione a data de nascimento do aluno.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de Nascimento'),
        ),
    ]
