# Generated by Django 6.0.7 on 2026-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0026_alter_alunocurso_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='matriculado_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Informe a data/hora da matrícula.'),
        ),
    ]
