# Generated by Django 6.0 on 2026-08-13 20:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorecido', models.CharField(help_text='Informe o nome do favorecido.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Favorecido')),
                ('documento', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CNPJ')),
                ('data_vencimento', models.DateField(help_text='Informe a data de vencimento', verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(help_text='Informe a data de pagamento', verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Informe um valor entre R$ 0.01 e R$ 100.000,00', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000.00'))], verbose_name='Valor R$')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], help_text='Selecione o tipo de Pessoa', max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('tipo_conta', models.CharField(choices=[('PAGAR', 'A Pagar'), ('RECEBER', 'A Receber')], help_text='Selecione o tipo de conta', max_length=10, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Tipo de conta')),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Em Aberto', 'Em Aberto'), ('Cancelado', 'Cancelado')], help_text='Status da conta', max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Status da cobrança')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
