# Generated by Django 6.0 on 2026-08-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_pagamento',
            field=models.DateField(help_text='Informe a data de pagamento', verbose_name='Data de Pagamento'),
        ),
    ]
