# Generated by Django 6.0.6 on 2026-07-02 20:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Qual o código do vôo?', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Código do Vôo:')),
                ('data_horario', models.DateTimeField(help_text='Escolha a data e hora da partida.', verbose_name='Data e hora da partida.')),
                ('origem', models.CharField(help_text='Informe a origem do vôo', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('destino', models.CharField(help_text='Informe o destino do vôo', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'verbose_name_plural': 'Vôos',
            },
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveSmallIntegerField(help_text='Informe o número da passagem no Voo', verbose_name='Número da passagem')),
                ('passageiro', models.CharField(help_text='Imforme o nome do passageiro.', max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('emitida', 'Emitida'), ('em processamento', 'Em Processamento'), ('cancelada', 'Cancelada')], help_text='Selecione o atual status da passagem', max_length=20)),
                ('poltrona', models.CharField(help_text='Informe a localização da poltrona', max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('voo', models.ForeignKey(help_text='Selecione o vôo comercial', on_delete=django.db.models.deletion.PROTECT, to='exemplos.voo', verbose_name='Vôo Comercial')),
            ],
            options={
                'verbose_name_plural': 'Passagens',
                'unique_together': {('nr', 'voo'), ('passageiro', 'voo')},
            },
        ),
    ]
