# Generated by Django 6.0.6 on 2026-07-02 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(help_text='Informe o código da companhia', max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código Grêmionacional')),
                ('cidade', models.CharField(help_text='Informe a cidade do aeroporto', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(help_text='Informe o país do aeroporto.', max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='País')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
