# Generated by Django 6.0.6 on 2026-07-02 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0002_aeroporto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da CIA Aérea.', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cod', models.CharField(help_text='Informe o código entre 3 a 20 digitos', max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Código da CIA')),
                ('nr_voos', models.PositiveSmallIntegerField(default=1, help_text='Informe a quantidade de vôos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Vôos')),
                ('aeroportos', models.ManyToManyField(to='exemplos.aeroporto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
