# Generated by Django 6.0.6 on 2026-07-07 17:22

import datetime
import django.core.validators
import exemplos.validators.validador_cpf
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exemplos', '0004_aluno_disciplina_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='', help_text='O CPF deve ser válido e conter 11 dígitos.', max_length=14, validators=[exemplos.validators.validador_cpf.ValidadorCPF()], verbose_name='CPF do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today, help_text='Insira a data de nascimento no formato YYYY-MM-DD.', verbose_name='Data de nascimento do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='', help_text='Insira um email válido.', max_length=100, verbose_name='Email do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Transgênero Masculino', 'Transmasc'), ('Transgênero Feminino', 'Transfem'), ('Outro', 'Outro')], default='Outro', help_text='Selecione o gênero do aluno.', max_length=21, verbose_name='Gênero do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='Wellinguyngton Silva Dior', help_text='O nome deve conter pelo menos 3 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome do aluno'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, help_text='Insira um telefone válido com DDD.', max_length=15, null=True, verbose_name='Telefone do aluno'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(choices=[('Matemática', 'Matematica'), ('Português', 'Portugues'), ('História', 'Historia'), ('Geografia', 'Geografia'), ('Ciências', 'Ciencias'), ('Artes', 'Artes'), ('Educação Física', 'Educacao Fisica'), ('Informática', 'Informatica')], default='Matemática', help_text='Selecione a disciplina.', max_length=100, verbose_name='Nome da disciplina'),
        ),
    ]
