# Generated by Django 6.0.6 on 2026-06-11 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='O titulo deve conter pelomenos 5 e maximo 100', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Titulo do jogador')),
                ('descricao', models.TextField(blank=True, help_text='(OPCIONAL) Informe a descrição do exemplo com no minimo 10 caracteres e maximo 5000, essa descrição ficará disponível para o usuário.', max_length=5000, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='🧛Descrição🧛')),
                ('qualidade', models.IntegerField(default=0, help_text='A qualidade do exemplo deve estar entre 0 e 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualidade')),
                ('nota', models.FloatField(help_text='A nota deve estar entre 0.0 e 10.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota')),
            ],
            options={
                'verbose_name_plural': '🤾🏻\u200d♂️Jogadores🤾🏻\u200d♂️',
            },
        ),
    ]
