# Generated by Django 6.0.6 on 2026-06-17 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='A marca deve conter pelomenos 2 e maximo 25 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Qual a marca do carro?')),
                ('modelo', models.CharField(help_text='O modelo deve conter pelo menos entre 2 e 25 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Qual o modelo do carro?')),
                ('ano', models.IntegerField(default=0, help_text='O ano deve ser ascima de 1900 até a data atual.', validators=[django.core.validators.MaxValueValidator(2026), django.core.validators.MinValueValidator(1900)], verbose_name='Ano de fabricação.')),
                ('placa', models.CharField(help_text='Deve conter 8 caracteres.', max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)], verbose_name='Qual a placa do carro?')),
                ('chassi', models.CharField(help_text='O chassi deve ter exatamente 13 caracteres.', max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='Qual o chassi do carro?')),
                ('cor', models.CharField(help_text='A cor deve ter no mínimo 4 caracteres e no máximo 20', max_length=20, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(20)], verbose_name='Qual a cor do carro?')),
                ('cor_lateral', models.CharField(help_text='A cor deve ter no mínimo 4 caracteres e no máximo 20', max_length=20, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(20)], verbose_name='Qual a cor do carro?')),
                ('velocidade', models.FloatField(help_text='A velocidade deve ser maior que zero e menor que 500.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Qual a velocidade máxima do carro?')),
                ('tipo_combustivel', models.CharField(help_text='Deve ter entre 2 e 15 caracteres.', max_length=15, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(15)], verbose_name='Qual tipo de combustível ele usa?')),
            ],
            options={
                'verbose_name_plural': '🚗Carros️🚗',
            },
        ),
    ]
