# Generated by Django 6.0.6 on 2026-06-17 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cor_lateral',
            field=models.CharField(help_text='A cor deve ter no mínimo 4 caracteres e no máximo 20', max_length=20, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(20)], verbose_name='Qual a cor lateral do carro?'),
        ),
    ]
