# Generated by Django 6.0.6 on 2026-06-17 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_alter_carro_cor_lateral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Byd', 'Build Your Dreams - BYD'), ('Volkswagen', 'Volkswagen - VM'), ('Volvo', 'Volvo'), ('Renault', 'Renault'), ('Fiat', 'Fiat')], default='Byd', help_text='A marca deve conter pelomenos 2 e maximo 25 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Qual a marca do carro?'),
        ),
    ]
