# Generated by Django 6.0.6 on 2026-06-18 20:13

import clube.validators.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0004_alter_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='numeros_pares',
            field=models.IntegerField(default=0, help_text='Insira o seu número escolhido. Lembre-se que apenas são aceitos números pares e únicos.', unique=True, validators=[clube.validators.functions.validation_even], verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.IntegerField(choices=[(1, 'Azul'), (2, 'Preto'), (3, 'Branco')], default=1, max_length=20, verbose_name='Qual a cor do carro?'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='marca',
            field=models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Byd', 'Build Your Dreams - BYD'), ('Volkswagen', 'Volkswagen - VM'), ('Volvo', 'Volvo'), ('Renault', 'Renault'), ('Fiat', 'Fiat')], default='Byd', max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
