# Generated by Django 6.0.6 on 2026-06-18 21:07

import clube.validators.code
import clube.validators.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0005_carro_numeros_pares_alter_carro_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='codigo',
            field=models.IntegerField(blank=True, help_text='insira o código', null=True, validators=[clube.validators.code.CodeValidator(100)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='numeros_pares',
            field=models.IntegerField(default=0, help_text='Insira o seu número escolhido. Lembre-se que apenas são aceitos números pares e únicos.', unique=True, validators=[clube.validators.functions.validation_even, clube.validators.code.CodeValidator(200)], verbose_name='Número'),
        ),
    ]
