# Generated by Django 6.0.6 on 2026-06-18 21:49

import clube.validators.palavras_proibidas
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0006_carro_codigo_alter_carro_numeros_pares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='modelo',
            field=models.CharField(help_text='O modelo deve conter pelo menos entre 2 e 25 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(2), clube.validators.palavras_proibidas.PalavrasProibidas(['Inter', 'Colorado'])], verbose_name='Qual o modelo do carro?'),
        ),
    ]
