# Generated by Django 6.0.6 on 2026-06-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0007_alter_carro_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cor',
            field=models.IntegerField(choices=[(1, 'Azul'), (2, 'Preto'), (3, 'Branco')], default=1, verbose_name='Qual a cor do carro?'),
        ),
    ]
