# Generated by Django 6.0.6 on 2026-06-24 20:14

import clube.validators.functions
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0008_alter_carro_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Porsche', 'Porsche'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Bugatti', 'Bugatti'), ('Ford', 'Ford'), ('Tesla', 'Tesla')], default='Porsche', max_length=20, validators=[django.core.validators.MinLengthValidator(4)])),
                ('modelo', models.CharField(help_text='O modelo deve conter pelo menos entre 2 e 25 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)], verbose_name='Qual o modelo do carro?')),
                ('ano', models.IntegerField(default=0, help_text='O ano deve ser ascima de 1900 até a data atual.', validators=[clube.validators.functions.validation_ano_do_modelo], verbose_name='Ano de fabricação.')),
                ('placa', models.CharField(help_text='Deve conter 7 caracteres.', max_length=7, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)], verbose_name='Qual a placa do carro?')),
                ('valor_diaria', models.IntegerField(default=200, help_text='insira a diária', validators=[django.core.validators.MinValueValidator(200)], verbose_name='Valor da diária')),
                ('seguro', models.FloatField(help_text='O seguro deve ser maior que 50.', validators=[django.core.validators.MinValueValidator(50)], verbose_name='Qual o valor do seguro do carro?')),
                ('ultima_revisao', models.DateField(help_text='A revisão não deve ter data maior que a atual.', validators=[django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Ultima Revisão.')),
                ('ipva', models.BooleanField(default=False, help_text='Deve confirmar se o IPVA está em dia.', verbose_name='IPVA pago?')),
                ('alugado', models.BooleanField(default=False, verbose_name='O carro está alugado atualmente?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nota',
            field=models.FloatField(editable=False, help_text='A nota deve estar entre 0.0 e 10.0.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota'),
        ),
    ]
