# Generated by Django 6.0.6 on 2026-07-06 15:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_voo', models.CharField(help_text='Código do voo (ex: AA1234)', max_length=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('origem', models.CharField(help_text='Cidade de origem (ex: São Paulo)', max_length=50, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Origem')),
                ('destino', models.CharField(help_text='Cidade de destino (ex: Rio de Janeiro)', max_length=50, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Destino')),
                ('data_ida', models.DateField(help_text='Data de ida (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 6))], verbose_name='Partida')),
                ('chegada', models.DateField(help_text='Data e hora de chegada (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 6))], verbose_name='Chegada')),
                ('titular', models.CharField(blank=True, help_text='Nome do titular da passagem (ex: João Silva)', max_length=150, null=True, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Titular')),
                ('passaporte', models.CharField(blank=True, help_text='Número do passaporte (ex: P1234567)', max_length=20, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Passaporte')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço da passagem (ex: 1500.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('companhia_aerea', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Passagens',
            },
        ),
    ]
