# Generated by Django 6.0.6 on 2026-07-06 18:23

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifacwc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(help_text='Nome do titular do ingresso (ex: João Silva)', max_length=150, validators=[django.core.validators.MinValueValidator(10)], verbose_name='Titular')),
                ('passaporte', models.CharField(blank=True, help_text='Número do passaporte (ex: P1234567)', max_length=20, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Passaporte')),
                ('data_compra', models.DateField(blank=True, help_text='Data da compra do ingresso (ex: 2024-06-01)', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 6))], verbose_name='Data da Compra')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do ingresso (ex: 500.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('estadio', models.CharField(help_text='Nome do estádio (ex: Estádio do Maracanã)', max_length=100, validators=[django.core.validators.MinValueValidator(3)], verbose_name='Estádio')),
                ('setor', models.CharField(choices=[('ST', 'Arquibancada (Stand)'), ('SE', 'Assento (Seat)'), ('CA', 'Cabine (Cabin)'), ('CO', 'Área Comum (Common Area)')], help_text='Setor do ingresso (ex: VIP - Área VIP)', max_length=50, verbose_name='Setor')),
                ('data_jogo', models.DateField(help_text='Data do jogo (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 6))], verbose_name='Data do Jogo')),
                ('fase', models.CharField(choices=[('GR', 'Grupo'), ('OIT', 'Oitavas de Final'), ('QUA', 'Quartas de Final'), ('SEM', 'Semifinal'), ('FIN', 'Final')], help_text='Fase do jogo (ex: GR - Grupo)', max_length=50, verbose_name='Fase')),
                ('cidade', models.CharField(help_text='Cidade do jogo (ex: Rio de Janeiro)', max_length=100, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Cidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='passagem',
            name='companhia_aerea',
            field=models.CharField(choices=[('OO', 'SkyWest Airlines'), ('DL', 'Delta Airlines'), ('UA', 'United Airlines'), ('AA', 'American Airlines'), ('WN', 'Southwest Airlines')], max_length=100),
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=150, validators=[django.core.validators.MinValueValidator(10)])),
                ('email', models.EmailField(help_text="Email do responsável pelo pacote (ex:'nome@exemplo.com)", max_length=254, validators=[django.core.validators.MinValueValidator(10)])),
                ('data_compra', models.DateField(help_text='Data da compra do pacote (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 6))], verbose_name='Data da Compra')),
                ('preco_total', models.DecimalField(decimal_places=2, help_text='Preço total do pacote (ex: 1000.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Total')),
                ('pagamento', models.CharField(choices=[('CC', 'Cartão de Crédito'), ('MO', 'Dinheiro'), ('PX', 'PIX')], help_text='Forma de pagamento do pacote (ex: CC - Cartão de Crédito)', max_length=50, verbose_name='Pagamento')),
                ('ingressos', models.ForeignKey(help_text='Selecione o ingresso do pacote', on_delete=django.db.models.deletion.PROTECT, to='fifacwc.ingresso', verbose_name='Ingresso')),
                ('passagens', models.ForeignKey(help_text='Selecione a passagem do pacote', on_delete=django.db.models.deletion.PROTECT, to='fifacwc.passagem', verbose_name='Passagem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
