# Generated by Django 6.0.6 on 2026-07-07 17:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifacwc', '0002_ingresso_alter_passagem_companhia_aerea_pacote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresso',
            name='cidade',
            field=models.CharField(help_text='Cidade do jogo (ex: Rio de Janeiro)', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='data_compra',
            field=models.DateField(blank=True, help_text='Data da compra do ingresso (ex: 2024-06-01)', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 7))], verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='data_jogo',
            field=models.DateField(help_text='Data do jogo (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 7))], verbose_name='Data do Jogo'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='estadio',
            field=models.CharField(help_text='Nome do estádio (ex: Estádio do Maracanã)', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Estádio'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='passaporte',
            field=models.CharField(blank=True, help_text='Número do passaporte (ex: P1234567)', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Passaporte'),
        ),
        migrations.AlterField(
            model_name='ingresso',
            name='titular',
            field=models.CharField(help_text='Nome do titular do ingresso (ex: João Silva)', max_length=150, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='data_compra',
            field=models.DateField(help_text='Data da compra do pacote (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 7))], verbose_name='Data da Compra'),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='email',
            field=models.EmailField(help_text="Email do responsável pelo pacote (ex:'nome@exemplo.com)", max_length=254, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pacote',
            name='nome_responsavel',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='chegada',
            field=models.DateField(help_text='Data e hora de chegada (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 7))], verbose_name='Chegada'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='cod_voo',
            field=models.CharField(help_text='Código do voo (ex: AA1234)', max_length=10, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='data_ida',
            field=models.DateField(help_text='Data de ida (ex: 2024-06-01)', validators=[django.core.validators.MinValueValidator(datetime.date(2026, 7, 7))], verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='destino',
            field=models.CharField(help_text='Cidade de destino (ex: Rio de Janeiro)', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='origem',
            field=models.CharField(help_text='Cidade de origem (ex: São Paulo)', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='passaporte',
            field=models.CharField(blank=True, help_text='Número do passaporte (ex: P1234567)', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Passaporte'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='titular',
            field=models.CharField(blank=True, help_text='Nome do titular da passagem (ex: João Silva)', max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Titular'),
        ),
    ]
