from .base import *
from .exemplo import *
from .carro import *
from .veiculo import *
from .pessoa import *
from .passaporte import *
from .aluno import *
from .bolsa import *
from .voo import *
from .passagem import *
from .aeroporto import *
from .comp_aerea import *
from .aluno_curso import *
from .disciplina import *
from .matricula import *